### PR TITLE
feat: add icon component

### PR DESCRIPTION
**Pull request by gizemnkorkmaz**
Icon component uses a selection.json file which contains the SVG paths for all the icons. All the needed information can be found in the Icon.md file. Added a small icon to Header just to demonstrate the usage of the component.

### CODE REVIEW

**Comment by OrhanOzkercin** [comment]
Well done Gizem 👏

As far as I understand this library helps us to organize all our icons in a single JSON file. But let's say we found an SVG and add that JSON file and another time we need another SVG are we adding that SVG to the end of the array in the JSON file or is there any way to organize it automatically?

**Comment by gizemnkorkmaz** [comment]
Thank you @OrhanOzkercin :)
Of course, you can! As I added all the required links to the md file, you can use https://svgps.app/app/ or https://icomoon.io/app/#/select for this kind of automation. You need to import the current JSON file and update your list with the new icons and download the latest version of your JSON file.

**Review by OrhanOzkercin — APPROVED** [review]
Looks good to me 👏

**Comment by eraygundogmus** [comment]
LGTM!

**Pull request merged**
